// Static reference data for the recommendation & simulation engines.
// Historical CAGR figures are long-run averages for educational estimation only —
// not predictions. Ranges (low/high) drive the best/worst-case simulator bands.

const INSTRUMENT_CATALOG = [
  {
    id: "nifty50",
    name: "Nifty 50 Index Fund",
    category: "Equity - Index",
    historicalCAGR: 12,
    cagrRange: { low: 7, high: 15 },
    riskLevel: "Medium-High",
    riskScore: 4,
    minHorizonYears: 5,
    liquidity: "High (open-ended, redeemable in 1-3 days)",
    taxBenefits: "LTCG taxed at 12.5% above ₹1.25L/year gains (>1 year holding)",
    pros: ["Broad exposure to India's 50 largest companies", "Low expense ratio", "Historically strong long-term compounding"],
    cons: ["Short-term volatility", "No capital protection", "Returns not guaranteed"],
  },
  {
    id: "sensex",
    name: "Sensex Index Fund",
    category: "Equity - Index",
    historicalCAGR: 11.5,
    cagrRange: { low: 6.5, high: 14.5 },
    riskLevel: "Medium-High",
    riskScore: 4,
    minHorizonYears: 5,
    liquidity: "High (open-ended, redeemable in 1-3 days)",
    taxBenefits: "LTCG taxed at 12.5% above ₹1.25L/year gains (>1 year holding)",
    pros: ["Tracks India's 30 largest, most-established companies", "Long track record", "Diversified across sectors"],
    cons: ["Correlated with overall market downturns", "No guaranteed returns"],
  },
  {
    id: "fd",
    name: "Fixed Deposit",
    category: "Debt - Fixed Income",
    historicalCAGR: 6.5,
    cagrRange: { low: 5.5, high: 7.5 },
    riskLevel: "Low",
    riskScore: 1,
    minHorizonYears: 0.5,
    liquidity: "Low-Medium (premature withdrawal penalty typically applies)",
    taxBenefits: "Interest fully taxable; 5-year tax-saver FD qualifies under Section 80C",
    pros: ["Capital protected", "Guaranteed, fixed return", "Simple to open with any bank"],
    cons: ["Returns often barely beat inflation", "Interest fully taxable", "Penalty on early withdrawal"],
  },
  {
    id: "ppf",
    name: "Public Provident Fund (PPF)",
    category: "Debt - Government",
    historicalCAGR: 7.1,
    cagrRange: { low: 6.8, high: 8 },
    riskLevel: "Low",
    riskScore: 1,
    minHorizonYears: 15,
    liquidity: "Low (15-year lock-in, partial withdrawal from year 7)",
    taxBenefits: "EEE status - contribution, interest and maturity all tax-free under Section 80C",
    pros: ["Government-backed, sovereign guarantee", "Fully tax-free returns", "Good for retirement-horizon goals"],
    cons: ["Long 15-year lock-in", "Contribution capped at ₹1.5L/year", "Not liquid for short-term needs"],
  },
  {
    id: "debt_fund",
    name: "Debt Mutual Fund",
    category: "Debt - Market Linked",
    historicalCAGR: 7,
    cagrRange: { low: 5, high: 9 },
    riskLevel: "Low-Medium",
    riskScore: 2,
    minHorizonYears: 1,
    liquidity: "High (open-ended, redeemable in 1-2 days)",
    taxBenefits: "Gains taxed at slab rate (post-2023 rules, no indexation benefit)",
    pros: ["More liquid than FDs", "Lower volatility than equity", "Useful for short-to-medium goals"],
    cons: ["Interest-rate sensitive", "No capital guarantee", "Credit risk in lower-quality funds"],
  },
  {
    id: "gold_etf",
    name: "Gold ETF",
    category: "Commodity",
    historicalCAGR: 9,
    cagrRange: { low: 4, high: 13 },
    riskLevel: "Medium",
    riskScore: 3,
    minHorizonYears: 3,
    liquidity: "High (traded on exchange like a stock)",
    taxBenefits: "LTCG at 12.5% after 1 year holding (post-2024 rules)",
    pros: ["Hedge against inflation and rupee depreciation", "No storage/purity concerns unlike physical gold", "Easily tradable"],
    cons: ["No income/dividend", "Price can stay flat for long stretches", "Tracking error vs physical gold"],
  },
  {
    id: "sgb",
    name: "Sovereign Gold Bond (SGB)",
    category: "Government - Commodity Linked",
    historicalCAGR: 9.5,
    cagrRange: { low: 4.5, high: 13.5 },
    riskLevel: "Medium",
    riskScore: 3,
    minHorizonYears: 8,
    liquidity: "Low (8-year tenure; exit via exchange listing possible after year 5)",
    taxBenefits: "Capital gains tax-free if held to maturity; 2.5% annual interest is taxable",
    pros: ["Extra 2.5% p.a. interest on top of gold price gains", "Sovereign-backed, no default risk", "Tax-free gains at maturity"],
    cons: ["Long tenure", "Limited liquidity before maturity", "New tranches not always open for subscription"],
  },
  {
    id: "mutual_fund",
    name: "Diversified Equity Mutual Fund",
    category: "Equity - Actively Managed",
    historicalCAGR: 13,
    cagrRange: { low: 6, high: 17 },
    riskLevel: "Medium-High",
    riskScore: 4,
    minHorizonYears: 5,
    liquidity: "High (open-ended, redeemable in 1-3 days)",
    taxBenefits: "LTCG taxed at 12.5% above ₹1.25L/year gains (>1 year holding)",
    pros: ["Professional fund management", "Diversified across sectors/caps", "SIP-friendly for disciplined investing"],
    cons: ["Fund manager risk", "Expense ratio higher than index funds", "Performance varies fund-to-fund"],
  },
  {
    id: "corporate_bond",
    name: "Corporate Bonds",
    category: "Debt - Credit",
    historicalCAGR: 8,
    cagrRange: { low: 6, high: 10.5 },
    riskLevel: "Medium",
    riskScore: 3,
    minHorizonYears: 2,
    liquidity: "Medium (secondary market can be thin for some issuers)",
    taxBenefits: "Interest taxed at slab rate; no special exemption",
    pros: ["Higher yield than government bonds", "Fixed coupon income", "Range of tenures available"],
    cons: ["Credit/default risk depends on issuer rating", "Less liquid than mutual funds", "Interest fully taxable"],
  },
];

module.exports = { INSTRUMENT_CATALOG };
